### ISSUE TITLE
Feed Issue on Hub

### ISSUE THREAD

**Issue by robertmuehsig** [Code-Inside/Blog#16]
[08/31/2014 22:20:23 > 73746b: ERR ] 
[08/31/2014 22:20:23 > 73746b: ERR ] Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.Xml.XmlException: Error in line 8 position 51. An error was encountered when parsing a DateTime value in the XML.
[08/31/2014 22:20:23 > 73746b: ERR ]    at System.ServiceModel.Syndication.Rss20FeedFormatter.DateFromString(String dateTimeString, XmlReader reader)
[08/31/2014 22:20:23 > 73746b: ERR ]    at System.ServiceModel.Syndication.Rss20FeedFormatter.ReadXml(XmlReader reader, SyndicationFeed result)
[08/31/2014 22:20:23 > 73746b: ERR ]    at System.ServiceModel.Syndication.Rss20FeedFormatter.ReadFeed(XmlReader reader)
[08/31/2014 22:20:23 > 73746b: ERR ]    at System.ServiceModel.Syndication.Rss20FeedFormatter.ReadFrom(XmlReader reader)
[08/31/2014 22:20:23 > 73746b: ERR ]    at System.ServiceModel.Syndication.SyndicationFeed.Load[TSyndicationFeed](XmlReader reader)
[08/31/2014 22:20:23 > 73746b: ERR ]    at CodeInside.Domain.Feed.FeedCrawler.GetFeed(String url)
[08/31/2014 22:20:23 > 73746b: ERR ]    at CodeInside.Domain.Feed.FeedCrawler.<DoWorkAsync>d__2.MoveNext()
[08/31/2014 22:20:23 > 73746b: ERR ] --- End of stack trace from previous location where exception was thrown ---
[08/31/2014 22:20:23 > 73746b: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[08/31/2014 22:20:23 > 73746b: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[08/31/2014 22:20:23 > 73746b: ERR ]    at CodeInside.Domain.MasterCrawler.<RunAllCrawlers>d__0.MoveNext()
[08/31/2014 22:20:23 > 73746b: ERR ]    --- End of inner exception stack trace ---
[08/31/2014 22:20:23 > 73746b: ERR ]    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
[08/31/2014 22:20:23 > 73746b: ERR ]    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
[08/31/2014 22:20:23 > 73746b: ERR ]    at System.Threading.Tasks.Task`1.get_Result()
[08/31/2014 22:20:23 > 73746b: ERR ]    at CodeInside.Crawler.Program.Main()

**Comment by robertmuehsig** [comment]
Reason for this: The RSS Feed had a wrong date format - correct date format for RSS is RFC822. Fixed
